title: AfterData
url: "https://afterdata.in"
baseurl: ""
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Uma novo conceito de Data Science para o Norte Paranaense!

# Author details for the jekyll-seo-tag gem
author:
  name: After Data
  email: contato@afterdata.in
  twitter:

# Social details for the jekyll-seo-tag gem
social:
  name: After Data
  links:
    - https://github.com/CloudCannon/urban-jekyll-template

timezone: Etc/UTC

collections:
  members:
    output: false
  events:
    output: true
  jobs:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000

  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "members"
    values:
      _options:
        image_path:
          width: 600
          height: 600

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

social_icons:
  - Facebook
  - twitter
  - Instagram
  - Linkedin
  - Pinterest
  - Trakt
  - Github
  - StackExchange
  - Devto
  - Telegram
  - Keybase
